### ISSUE TITLE
Lots of issues with unsupported packages

### ISSUE THREAD

**Issue by jimoquinn** [fleetbase/docs#6]
Attempted to build the docs and found there are a considerable number of outdated packages and unsupported packages.

yarn
! Corepack is about to download https://registry.yarnpkg.com/yarn/-/yarn-1.22.22.tgz
? Do you want to continue? [Y/n] y

! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager

yarn install v1.22.22
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @docusaurus/core > del > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @docusaurus/core > webpack-dev-server > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @docusaurus/core > shelljs > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @docusaurus/core > del > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @docusaurus/core > react-dev-utils > fork-ts-checker-webpack-plugin > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @docusaurus/core > shelljs > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning @docusaurus/core > react-dev-utils > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @docusaurus/core > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @docusaurus/core > @svgr/webpack > @svgr/plugin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/use-modal@0.3.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/api-client > @scalar/use-modal@0.3.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-node-ofetch@0.1.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-core@0.1.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-node-ofetch > @scalar/snippetz-core@0.1.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-js-fetch@0.1.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-js-fetch > @scalar/snippetz-core@0.1.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-js-ofetch@0.1.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-js-ofetch > @scalar/snippetz-core@0.1.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-node-fetch@0.1.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-node-fetch > @scalar/snippetz-core@0.1.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-node-undici@0.1.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/snippetz > @scalar/snippetz-plugin-node-undici > @scalar/snippetz-core@0.1.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@docusaurus/core > react-loadable-ssr-addon-v5-slorber@1.0.1" has unmet peer dependency "react-loadable@*".
warning "@docusaurus/core > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.3" has unmet peer dependency "typescript@>= 2.7".
warning "@docusaurus/core > @docusaurus/mdx-loader > @mdx-js/mdx > recma-jsx > acorn-jsx@5.3.2" has unmet peer dependency "acorn@^6.0.0 || ^7.0.0 || ^8.0.0".
warning " > @mdx-js/react@3.1.0" has unmet peer dependency "@types/react@>=16".
warning "@docusaurus/preset-classic > @docusaurus/plugin-debug > @microlink/react-json-view > flux@4.0.4" has incorrect peer dependency "react@^15.0.2 || ^16.0.0 || ^17.0.0".
warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-preset-algolia@1.17.7" has unmet peer dependency "@algolia/client-search@>= 4.9.1 < 6".
warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-preset-algolia > @algolia/autocomplete-shared@1.17.7" has unmet peer dependency "@algolia/client-search@>= 4.9.1 < 6".
warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-core > @algolia/autocomplete-plugin-algolia-insights@1.17.7" has unmet peer dependency "search-insights@>= 1 < 3".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference@1.22.56" has unmet peer dependency "unified@^11.0.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference@1.22.56" has unmet peer dependency "vue@^3.3.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > postcss-nested@6.2.0" has unmet peer dependency "postcss@^8.2.14".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/themes@0.7.11" has unmet peer dependency "vue@^3.3.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @headlessui/vue@1.7.23" has unmet peer dependency "vue@^3.2.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/use-modal@0.3.3" has unmet peer dependency "vue@^3.3.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/api-client@1.2.39" has unmet peer dependency "vue@^3.3.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/use-toasts@0.6.7" has unmet peer dependency "nanoid@4 - 5".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/use-toasts@0.6.7" has unmet peer dependency "vue@^3.3.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/use-toasts@0.6.7" has unmet peer dependency "vue-sonner@^1.0.3".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/components@0.8.0" has unmet peer dependency "vue@^3.3.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/use-tooltip@0.6.2" has unmet peer dependency "vue@^3.3.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @vueuse/core > vue-demi@0.14.10" has unmet peer dependency "vue@^3.0.0-0 || ^2.6.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @headlessui/vue > @tanstack/vue-virtual@3.10.9" has unmet peer dependency "vue@^2.7.0 || ^3.0.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/components > @storybook/test@8.4.5" has unmet peer dependency "storybook@^8.4.5".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/api-client > @scalar/use-codemirror@0.10.5" has unmet peer dependency "vue@^3.3.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/api-client > @scalar/use-codemirror@0.10.5" has unmet peer dependency "y-codemirror.next@^0.3.2".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/api-client > @scalar/use-codemirror@0.10.5" has unmet peer dependency "yjs@^13.6.0".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/components > @storybook/test > @storybook/instrumenter@8.4.5" has unmet peer dependency "storybook@^8.4.5".
warning "@scalar/docusaurus > @scalar/api-reference-react > @scalar/api-reference > @scalar/api-client > @scalar/use-codemirror > y-codemirror.next@0.3.5" has unmet peer dependency "yjs@^13.5.6".
warning " > docusaurus-plugin-image-zoom@2.0.0" has unmet peer dependency "@docusaurus/theme-classic@>=3.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 56.66s.

**Comment by roncodes** [comment]
Use pnpm hence the pnpm lockfile
